[tasks.check]
depends = [":check:*"]

[tasks.fix]
depends = [":fix:*"]

[tasks."check:tsc"]
extends = "ts:check:tsc"
sources = ["{src/**/*,playwright.config}.ts", "tsconfig.json", "{{vars.repo_root}}/packages/dev-config/tsconfig.base.json"]

[tasks."check:lint"]
extends = "ts:check:lint"

[tasks."check:format"]
extends = "ts:check:format"
run = "pnpm exec prettier --check 'src/**/*.ts' 'playwright.config.ts'"
sources = ["{src/**/*,playwright.config}.ts", "{{vars.repo_root}}/.prettierrc"]

[tasks."fix:lint"]
extends = "ts:fix:lint"

[tasks."fix:format"]
extends = "ts:fix:format"
run = "pnpm exec prettier --write 'src/**/*.ts' 'playwright.config.ts'"
