export const TIMELINE_MAX_SINCE_HOURS = 720;

export const TIMELINE_DEFAULT_SINCE_HOURS = 24;

export const TIMELINE_MAX_TRACES = 500;

export const TIMELINE_DEFAULT_TRACES = 100;

export const TIMELINE_MAX_SPANS = 2000;

export const TIMELINE_DEFAULT_SPANS = 1000;

export const TIMELINE_MAX_LOGS = 2000;

export const TIMELINE_DEFAULT_LOGS = 1000;

export const TIMELINE_MAX_LOG_ROWS = 1000;

export const TIMELINE_DEFAULT_LOG_ROWS = 200;

export const TIMELINE_MAX_TRACE_HOURS = 6;

export const TIMELINE_EXPORT_MAX_ROWS = 50_000;
