// This file is auto-generated by the `update-kc-gen` command. Do not edit it manually.
// Hash: a04d2f71026df0b5773b9716edc8a54aa015beb83965759521357027189731d1


/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

import { lazy, Suspense, type ReactNode } from "react";

export type ThemeName = "platform";

export const themeNames: ThemeName[] = ["platform"];

export type KcEnvName = "PLATFORM_ALLOW_PASSWORD" | "PLATFORM_REQUEST_ACCESS_URL";

export const kcEnvNames: KcEnvName[] = ["PLATFORM_ALLOW_PASSWORD", "PLATFORM_REQUEST_ACCESS_URL"];

export const kcEnvDefaults: Record<KcEnvName, string> = {
  "PLATFORM_ALLOW_PASSWORD": "true",
  "PLATFORM_REQUEST_ACCESS_URL": ""
};

/**
 * NOTE: Do not import this type except maybe in your entrypoint. 
 * If you need to import the KcContext import it either from src/login/KcContext.ts or src/account/KcContext.ts.
 * Depending on the theme type you are working on.
 */
export type KcContext =
    | import("./login/KcContext").KcContext
    ;

declare global {
    interface Window {
        kcContext?: KcContext;
    }
}

export const KcLoginPage = lazy(() => import("./login/KcPage"));

export function KcPage(
    props: {
        kcContext: KcContext;
        fallback?: ReactNode;
    }
) {
    const { kcContext, fallback } = props;
    return (
        <Suspense fallback={fallback}>
            {(() => {
                switch (kcContext.themeType) {
                    case "login": return <KcLoginPage kcContext={kcContext} />;
                }
            })()}
        </Suspense>
    );
}

// NOTE: This is exported here only because in Webpack environnement it works differently
export const BASE_URL = import.meta.env.BASE_URL
