#!/usr/bin/env node
// Generate docs/adrs/index.md from ADR frontmatter.
//
// The index is a projection of the ADR log, never hand-maintained. Each ADR
// carries YAML frontmatter (id, title, status, supersedes, subsystem, tags,
// summary); this script reads them all, derives superseded status from the
// forward `supersedes` links, and renders the scannable index.
//
// Legacy ADRs without frontmatter fall back to the filename, the `# ADR-NNN:`
// heading, and the `**Status:**` line so the index generates before every
// record is migrated. Frontmatter takes precedence and enriches rows over time.
//
// Modes:
//   node scripts/adr-index.mjs            write docs/adrs/index.md
//   node scripts/adr-index.mjs --check    fail if the committed index drifts
//
// The `--check` mode is the gate wired into `mise run check` + CI. It mirrors
// db:check:generated: regenerate, diff against what is committed, fail closed.

import { readFileSync, writeFileSync, readdirSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const REPO_ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
// ADR_INDEX_DIR overrides the ADR directory (used by tests); defaults to docs/adrs.
const ADR_DIR = process.env.ADR_INDEX_DIR
  ? resolve(process.env.ADR_INDEX_DIR)
  : join(REPO_ROOT, "docs", "adrs");
const INDEX_PATH = join(ADR_DIR, "index.md");
const GENERATED_MARKER =
  "<!-- generated by scripts/adr-index.mjs, do not edit — run `mise run docs:generate:adr-index` -->";

const STATUS = { ACCEPTED: "accepted", PROPOSED: "proposed", DEPRECATED: "deprecated" };

function splitFrontmatter(raw) {
  if (!raw.startsWith("---\n")) return { frontmatter: null, body: raw };
  const end = raw.indexOf("\n---", 4);
  if (end === -1) return { frontmatter: null, body: raw };
  const fm = raw.slice(4, end);
  const bodyStart = raw.indexOf("\n", end + 1);
  return { frontmatter: fm, body: bodyStart === -1 ? "" : raw.slice(bodyStart + 1) };
}

function unquote(v) {
  const t = v.trim();
  if ((t.startsWith('"') && t.endsWith('"')) || (t.startsWith("'") && t.endsWith("'"))) {
    return t.slice(1, -1);
  }
  return t;
}

// Minimal YAML for the flat ADR frontmatter schema: `key: scalar`, inline
// `key: [a, b]` lists, and block `- item` lists. No nesting beyond that.
function parseFrontmatter(fm) {
  const out = {};
  const lines = fm.split("\n");
  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];
    if (!line.trim() || line.trimStart().startsWith("#")) continue;
    const m = line.match(/^([A-Za-z_][\w-]*):\s*(.*)$/);
    if (!m) continue;
    const key = m[1];
    let value = m[2];
    if (value === "" || value === "|" || value === ">") {
      const items = [];
      while (i + 1 < lines.length && /^\s*-\s+/.test(lines[i + 1])) {
        items.push(unquote(lines[++i].replace(/^\s*-\s+/, "")));
      }
      out[key] = items.length ? items : "";
      continue;
    }
    if (value.startsWith("[") && value.endsWith("]")) {
      out[key] = value
        .slice(1, -1)
        .split(",")
        .map((s) => unquote(s))
        .filter(Boolean);
      continue;
    }
    out[key] = unquote(value);
  }
  return out;
}

function padId(id) {
  if (id == null || id === "") return null;
  const n = String(id).trim();
  return /^\d+$/.test(n) ? n.padStart(3, "0") : n;
}

function normalizeStatus(raw) {
  const s = String(raw || "").trim().toLowerCase();
  if (s.startsWith("superseded")) {
    const m = s.match(/(\d+)/);
    return { status: STATUS.ACCEPTED, supersededBy: m ? padId(m[1]) : null };
  }
  if (s.startsWith("deprecat")) return { status: STATUS.DEPRECATED };
  if (s.startsWith("propos")) return { status: STATUS.PROPOSED };
  return { status: STATUS.ACCEPTED };
}

// Fallback for legacy ADRs: `# ADR-NNN: Title` heading and `**Status:** ...`.
function parseLegacyBody(body) {
  const out = {};
  const heading = body.match(/^#\s+(?:ADR-\d+:\s*)?(.+?)\s*$/m);
  if (heading) out.title = heading[1].trim();
  const status = body.match(/^\*\*Status:\*\*\s*(.+?)\s*$/m);
  if (status) out.status = status[1].trim();
  return out;
}

function toArray(v) {
  if (v == null || v === "") return [];
  return Array.isArray(v) ? v : [v];
}

function loadAdrs() {
  const files = readdirSync(ADR_DIR)
    .filter((f) => f.endsWith(".md") && f !== "index.md")
    .sort();

  const records = files.map((file) => {
    const raw = readFileSync(join(ADR_DIR, file), "utf8");
    const { frontmatter, body } = splitFrontmatter(raw);
    const fm = frontmatter ? parseFrontmatter(frontmatter) : {};
    const legacy = parseLegacyBody(body);
    const isDraft = /^DRAFT-/i.test(file);
    const idFromName = file.match(/^(\d{3})-/);

    const id = padId(fm.id) || (idFromName ? idFromName[1] : null);
    const title = fm.title || legacy.title || file.replace(/\.md$/, "");
    const norm = normalizeStatus(fm.status || legacy.status || (isDraft ? "proposed" : "accepted"));

    return {
      file,
      id,
      isDraft,
      title,
      status: norm.status,
      supersededByHint: norm.supersededBy || null,
      supersedes: toArray(fm.supersedes).map((x) => padId(x)).filter(Boolean),
      subsystem: fm.subsystem || "",
      tags: toArray(fm.tags),
      summary: fm.summary || "",
    };
  });

  const byId = new Map();
  for (const r of records) if (r.id) byId.set(r.id, r);

  // Derive superseded status from forward links (authoritative) plus any legacy
  // "Superseded by NNN" status line (back-compat until frontmatter lands).
  const supersededBy = new Map();
  for (const r of records) {
    for (const target of r.supersedes) {
      if (r.id) supersededBy.set(target, r.id);
    }
    if (r.supersededByHint && r.id && !supersededBy.has(r.id)) {
      supersededBy.set(r.id, r.supersededByHint);
    }
  }

  for (const r of records) {
    r.supersededBy = r.id ? supersededBy.get(r.id) || null : null;
  }
  return { records, byId };
}

function esc(s) {
  return String(s).replace(/\|/g, "\\|").replace(/\n+/g, " ").trim();
}

function idSort(a, b) {
  if (a.id && b.id) return a.id.localeCompare(b.id);
  if (a.id) return -1;
  if (b.id) return 1;
  return a.file.localeCompare(b.file);
}

function renderTable(rows) {
  if (!rows.length) return "_None._\n";
  const header =
    "| ID | Title | Supersedes | Subsystem | Summary |\n" +
    "| --- | --- | --- | --- | --- |\n";
  const body = rows
    .map((r) => {
      const id = r.id || "DRAFT";
      const title = `[${esc(r.title)}](${r.file})`;
      const supersedes = r.supersedes.length ? r.supersedes.join(", ") : "";
      return `| ${id} | ${title} | ${supersedes} | ${esc(r.subsystem)} | ${esc(r.summary)} |`;
    })
    .join("\n");
  return header + body + "\n";
}

function renderSupersededTable(rows) {
  if (!rows.length) return "_None._\n";
  const header =
    "| ID | Title | Superseded by | Subsystem | Summary |\n" +
    "| --- | --- | --- | --- | --- |\n";
  const body = rows
    .map((r) => {
      const id = r.id || "DRAFT";
      const title = `[${esc(r.title)}](${r.file})`;
      return `| ${id} | ${title} | ${r.supersededBy || ""} | ${esc(r.subsystem)} | ${esc(r.summary)} |`;
    })
    .join("\n");
  return header + body + "\n";
}

function render({ records }) {
  const sorted = [...records].sort(idSort);
  const superseded = sorted.filter((r) => r.supersededBy);
  const live = sorted.filter((r) => !r.supersededBy);

  const accepted = live.filter((r) => !r.isDraft && r.status === STATUS.ACCEPTED);
  const deprecated = live.filter((r) => !r.isDraft && r.status === STATUS.DEPRECATED);
  const drafts = live.filter((r) => r.isDraft || r.status === STATUS.PROPOSED);

  return (
    `${GENERATED_MARKER}\n\n` +
    `# ADR Index\n\n` +
    `Generated projection of the ADR log. Read this first when authoring a new ` +
    `decision: scan the summaries, then open only the records that matter. ` +
    `Superseded status is derived from \`supersedes\` links, so an old record ` +
    `always shows its trajectory.\n\n` +
    `## Accepted\n\n${renderTable(accepted)}\n` +
    `## Superseded\n\n${renderSupersededTable(superseded)}\n` +
    `## Deprecated\n\n${renderTable(deprecated)}\n` +
    `## Drafts\n\n${renderTable(drafts)}`
  ).replace(/\n+$/, "\n");
}

function main() {
  const check = process.argv.includes("--check");
  const generated = render(loadAdrs());

  if (!check) {
    writeFileSync(INDEX_PATH, generated);
    process.stdout.write("✅ Wrote docs/adrs/index.md\n");
    return;
  }

  let current = "";
  try {
    current = readFileSync(INDEX_PATH, "utf8");
  } catch {
    current = "";
  }
  if (current !== generated) {
    process.stderr.write(
      "❌ docs/adrs/index.md is out of date. Run: mise run docs:generate:adr-index\n"
    );
    process.exit(1);
  }
  process.stdout.write("✅ docs/adrs/index.md matches the generated projection.\n");
}

main();
