[task_config]
includes = ["{{vars.repo_root}}/.mise/ts-package.toml", ".mise/tasks"]

[tasks."check:format"]
extends = "ts:check:format"
run = "pnpm exec prettier --check 'src/**/*.ts' '!src/proto-gen/**'"

[tasks."fix:format"]
extends = "ts:fix:format"
run = "pnpm exec prettier --write 'src/**/*.ts' '!src/proto-gen/**'"

[tasks.test]
extends = "ts:test"
run = "pnpm exec vitest run --config vitest.unit.config.ts"
sources = ["src/**", "vitest*.config.ts", "tsconfig.json", "{{vars.repo_root}}/pnpm-lock.yaml", "{{vars.repo_root}}/packages/vm-runner/contract/vocabulary.json"]
